CFLAGS=-Wall -Wextra -Wno-unused -Wno-unused-parameter -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++11

test: main.cpp
	g++ $(CFLAGS) main.cpp -o test

clean:
	rm -f *.o test


