
ifeq ($(KEYDIR),)
  $(error environment variable KEYDIR is not set)
endif

ifeq ($(KEYNAME),)
  $(error environment variable KEYNAME is not set)
endif

all:
	@ echo "KEYDIR=$(KEYDIR) NAME=$(KEYNAME)"



