#CFLAGS=-Wall -Wextra -Wno-unused -Wno-unused-parameter -Wconversion -std=c99
CFLAGS=-Wall -Wextra -Wno-unused -Wno-unused-parameter -std=c99 -O2

test: main.c
	gcc $(CFLAGS) main.c -o test

clean:
	rm -f *.o test


