CFLAGS=-Wall -Wextra -Wshadow -Wno-unused -Wno-unused-parameter -std=c99 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS

test: main.c
	gcc $(CFLAGS) main.c -o test

clean:
	rm -f *.o test


