CC=g++
#CC=arm-none-linux-gnueabi-g++

all:
	$(CC) UdpClient.cpp -o client -Wall -Wextra
	$(CC) UdpServer.cpp -o server -Wall -Wextra

normal:
	g++ UdpClient.cpp -o client -Wall -Wextra
	g++ UdpServer.cpp -o server -Wall -Wextra
